#!/bin/bash
set -e

function usage {
    cat <<EOT
Usage:
    $SCRIPTNAME url

Example of download and install:
    $SCRIPTNAME http://files.nette.org/NetteFramework-1.0alpha-PHP5.2.zip

Note:
    Created with Framework version is from date 15.9.2010.
EOT
}

function failure_msg {
    echo $1 >&2
    exit -1
}

SCRIPTNAME=$(basename $0)
if [ -f ./$SCRIPTNAME ]; then
    SCRIPTNAME=./$SCRIPTNAME
fi

if [ $# -ne 1 ]; then
    usage
    exit 0
else
    FRAMEWORK_URL=$1
fi


# check if folders exists and are writable
if [ ! -w . ]; then
    failure_msg "Permission denied for writing into folder `pwd`."
fi

if [ -d app ]; then
    failure_msg "Folder 'app' already exists. Framework is probably installed."
fi

ZIPFILE=`find . -maxdepth 1 -type f -name 'Nette*.zip'`
if [ -z "$ZIPFILE" ]; then
    # download framework
    wget $FRAMEWORK_URL
    ZIPFILE=`ls Nette*.zip`
fi

unzip $ZIPFILE
FRAMERORK_FOLDER=`find . -maxdepth 1 -type d -name 'Nette*'`

# copy skeleton: app, document_root, libs, readme.txt, tests
mv $FRAMERORK_FOLDER/skeleton/* .

# copy libs
mv $FRAMERORK_FOLDER/Nette libs
mv $FRAMERORK_FOLDER/3rdParty/dibi/dibi libs
mkdir libs-minified
mv $FRAMERORK_FOLDER/Nette-minified libs-minified
mv $FRAMERORK_FOLDER/3rdParty/dibi/dibi-minified libs-minified

# cleaning
rm -rf $FRAMERORK_FOLDER
rm $ZIPFILE

# set write privileges
chmod 777 app/log app/temp
